### PR TITLE
[IMP] [8.0] l10n_it_ddt

### PR DESCRIPTION
**Pull request by eLBati**
See commit messages and don't hesitate to ask if something is not clear.

Mainly:
- removed updateLines because introducing wrong and not clear behaviour
- used invoice_create_line to creat invoice, for better integration with existing flows
- tests

### CODE REVIEW

**Comment by LeartS** [comment]
The wizard (ddt from picking) + the `updateLines` on `create` resulted in DDTs with duplicate lines in the current tree verion, will test this PR to check the behavior is gone.

**Comment by LeartS** [comment]
Functional review:
- solves the duplicated lines problem, +1
- different behaviour on invoice creation: with this PR it wouldn't let me create an invoice if the DDT has a line with invoice control: not applicable, while I could before. I guess it's correct that it doesn't let me?, +1?
- Field labels on invoice creation wizard, +1

There are still some problems with the interpretation of "single DDT lines" and lines from pickings.
For example, try doing this:
- Open a picking with a single line not already in a DDT
- More -> DDT from pickings
- It should open a wizard with the picking and its line. Click create
- You are redirected to a new DDT with the single line (this is where it was duplicated before) in the DDT lines tab; and the picking in the pickings tab
- Delete the line from the lines tab, and add a custom one
- More -> create invoice

The invoice will still consider the picking line, even though we deleted it from the ddt lines.
(this already happened in the current HEAD, see https://github.com/abstract-open-solutions/l10n-italy/blob/8.0-ddt/l10n_it_ddt/wizard/ddt_create_invoice.py#L60)

**Comment by eLBati** [comment]
Thanks @LeartS , see this simple fix
https://github.com/eLBati/l10n-italy/commit/26d1fcc886cfe164c0d9bd312ceb5f68b3002d80

I would follow the concept: DDT document can only be created with dedicated wizard. This would reduce complexity and improve usability.
cc @dcorio

**Comment by dcorio** [comment]
@eLBati i'm not so sure that would be a good idea. in the real world i see DdTs modified very often within a single day. people (not the warehouse ops) create the ddt then start to add the deliverables mentioned in the SO or contract as per the deadlines, then move them from DdT to DdT, spit pickings and so till they get a DdT that can be approved. and this might take weeks.
this is why we decided to keep the ddt as a separated doc.

**Comment by OpenCode** [comment]
I agree with @dcorio . Also very often user need to insert description lines to be inserted between the product  lines and this can only be done separating DDT from the others documents

**Comment by lepistone** [comment]
@eLBati the new API can help you get rid of much boilerplate in your YAML tests. (not a blocker)

**Comment by dcorio** [comment]
@OpenCode that can be done anyway. what @eLBati proposed is to create the DdT via the "ddt from picking" wizard only (am i right?).
But this implies that the user already knows which are the final pickings.
Of course, the user can change the DdT even after it has been created, but i can't see this as a usability improvement.

**Comment by eLBati** [comment]
> what @eLBati proposed is to create the DdT via the "ddt from picking" wizard only (am i right?).

Right

> But this implies that the user already knows which are the final pickings.

I assumed a DDT can exist only if its pickings exist.
Would you consider other use cases? Can you describe them step by step? This would also make possible to implement the related test cases.
Thanks

**Comment by dcorio** [comment]
@eLBati of course. i'll share something asap

**Comment by LeartS** [comment]
Can we unlock the situation guys? Maybe @eLBati in the meantime you could propose a PR with the improvements except the last one which is being discussed? ATM the HEAD of the branch creates DDTs with duplicated lines, which is kinda bad..

**Comment by dcorio** [comment]
i planned to spend some other time on this the next week cause this is a key module for our customers too. but i can't right now.
in the meantime, any contribution will be appreciated.

**Comment by dcorio** [comment]
I merged this PR since it was including a lot of good fixes.
just one remark.
what if... the user would now add another picking to the existing ddt?
let say a new MO has ended and they're ready to deliver the goods.
usually companies don't create a new ddt if the first one is still to be delivered.

for this reason i'm in favor of leaving the picking_ids field editable.
what's your opinion?

**Comment by dcorio** [comment]
PS: i also fixed the "duplicated lines" issue

**Comment by FrancoTampieri** [comment]
I see that the computed field ddt_ids in the sale.order model is broken, so as soon as possible I put a fix.

Another questions, why the method action_ship_create is redefined two times in the sale.py? Can anyone tell me why we cam merge the function in one?

**Comment by eLBati** [comment]
Hello @drdran we fixed the issue you are citing in the branch https://github.com/hurrinico/l10n-italy/tree/hurrifix-8.0-ddt
We also made several other improvements, which are under testing. After that, we will make the PR

**Comment by LeartS** [comment]
@eLBati will the PR be against this or https://github.com/OCA/l10n-italy directly?

**Comment by FrancoTampieri** [comment]
@eLBati I'll test your branch and I tell you if there is some fixes to make.

**Pull request merged**
